### ISSUE TITLE
Readme.md should specify the project objective

### ISSUE THREAD

**Issue by HanyuWu** [udacity/CarND-Kidnapped-Vehicle-Project#46]
The reason I file this issue is because when I running my code in my local 1.8Ghz dual-core laptop, it becomes so hard to achieve the goal (24430 timestep in 100 seconds). Finally, I switched to the workspace provided by Udacity, and made it. I think someone would try using slow laptop to run the code at local like me, and that very drives me crazy.

**Comment by UAnjali** [comment]
Hi @HanyuWu,
Though we are late to respond, we hope that your issue is resolved. We encourage such _user-specific_ issues to be raised on the Knowledge hub so that our experienced mentors can chime in and new students can also learn from the discussion thread. Although, feel free to suggest an update to the starter code by raising a PR.
Happy Learning
Udacity
Thank you
